// <auto-generated />
using EMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.Models.TblEmployee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EMP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<string>("Department")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EMP_DEPARTMENT");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EMP_EMAIL");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EMP_NAME");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("EMP_STATUS");

                    b.HasKey("EmpId");

                    b.HasIndex("EmpId")
                        .IsUnique();

                    b.ToTable("TBL_EMPLOYEE", "dbo");
                });

            modelBuilder.Entity("EMS.Models.TblUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Role")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("USER_ROLE");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("USER_STATUS");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USER_NAME");

                    b.Property<string>("UserPassword")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("USER_PASSWORD");

                    b.HasKey("UserId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TBL_USER", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
